### ISSUE TITLE
non-english characters in names

### ISSUE THREAD

**Issue by Burikm** [wek32/strava-club-ytd#1]
hello, i got this:
7986413,\u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440,0.0,0.0
8700392,\u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u0412\u043e\u043b\u043a\u043e\u0432,0.0,0.0
7900293,\u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u041c\u043e\u0448\u043a\u0430\u0442\u044e\u043a,2738.7,11844.0
9317717,\u0410\u043d\u0434\u0440\u0435\u0439 \u0410\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u0435\u043d\u043a\u043e,3.0,0.0

unicode escaped characters insteed of normal symbols in names

**Comment by wek32** [comment]
Thanks for reporting this. I added unicode support on the branch unicode_support (https://github.com/wek32/strava-club-ytd/tree/unicode_support). I tested it out and it worked for me. Please test out this branch and report back. If it works for you I'll mainline the change.

Microsoft Excel didn't properly open the file directly ("File->Open"). To properly import to excel select "Data->From Text" in get external data, got this info on follow the guide:
http://help.tune.com/marketing-console/how-to-import-a-unicode-csv-to-excel/

Other text editors do support unicode characters with no surprises. Google Docs can also properly open the CSV file with unicode characters.

Can you post your strava club HTML file (the input to the scripts) so I can test it out and keep it for future testing.

**Comment by Burikm** [comment]
it works now, but only partially
then i try to get csv via command like 
python get_ytd_club_stats.py --html club_website_saved_by_club_owner.html --out ytd_stats.csv
i still get wrong characters insteed of names.

but if i do
python python extract_group_members.py --html club_website_saved_by_club_owner.html --out list_of_athletes.csv
python get_stats.py --members list_of_athletes.csv --out ytd_stats.csv
then i got nice list with ok names.

https://www.dropbox.com/s/ai0di2jmg4pyytq/ytd_stats.zip?dl=0

**Comment by wek32** [comment]
Thanks for catching this. Updated the branch with the fix, now both scripts should work.

Give it a try, it it works the change can be mainlined.

**Comment by Burikm** [comment]
aye, it works now, thanks!
